### ISSUE TITLE
404 on Atoms example page, perhaps due to routing

### ISSUE THREAD

**Issue by jwithington** [CSKingMartin/project-minotaur#2]
**Describe the bug**
404 Error when clicking on "Atoms.example.mdx"

**To Reproduce**
1. Install
2. Click on Atoms.example.mdx
3. See error

This also makes it so that any of the links in the footer no longer work. 

**Expected behavior**
Expected to see a page about Atom examples. 

**Screenshots**

<img width="1240" alt="404 screen" src="https://user-images.githubusercontent.com/4213550/58595634-3620d400-8226-11e9-86c9-3a112e08ab78.png">
^^ initial 404 screen

<img width="1186" alt="second 404 screen" src="https://user-images.githubusercontent.com/4213550/58595660-4769e080-8226-11e9-96db-cde7893bbaa3.png">
^^ after clicking around a bit (note URL)

**Desktop (please complete the following information):**
 - macOS 10.14.4
 - Chrome
 - Version 74.0.3729.169

**Comment by jwithington** [comment]
BTW: it seems that the footer links are kicking a 404 whenever I'm clicking from another element page, like http://localhost:3000/styleguide/molecules/Input or http://localhost:3000/styleguide/molecules/Expandable.  Seemingly only working properly from http://localhost:3000. 

🍻

**Comment by CSKingMartin** [comment]
Hey @jwithington this was a bug due to routing in Next.js.

In addressing this I've removed the 'Atoms.example.mdx' page, to be implemented later in clearer way.

The footer links now redirect correctly. You can see the commit addressing this here: https://github.com/CSKingMartin/project-minotaur/commit/31da56c99103d418ada802ad9d50ccb51cc4d43a

Closing 😁
